<a href="https://colab.research.google.com/github/dallalysalah/TP-Maths/blob/main/tp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.optimize import linprog


def generate_tabinitial(A, b, c):

    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1, 1)
    c = np.array(c, dtype=float)

    m, n = A.shape


    I = np.eye(m)
    A_bar = np.hstack([A, I])



    c_bar = np.concatenate([c, np.zeros(m)])


    T = np.zeros((m + 1, n + m + 1))


    T[:m, :n + m] = A_bar
    T[:m, -1] = b.flatten()


    T[-1, :n + m] = c_bar
    T[-1, -1] = 0.0

    return T


def positivite(v):

    v = np.array(v, dtype=float).flatten()
    min_val = np.min(v)
    idx_min = np.argmin(v)
    flag_pos = np.all(v >= 0)
    return flag_pos, min_val, idx_min


def rapportmin(b, a):

    b = np.array(b, dtype=float).flatten()
    a = np.array(a, dtype=float).flatten()

    ratios = []
    indices = []

    for i in range(len(b)):
        if a[i] > 0:
            ratios.append(b[i] / a[i])
            indices.append(i)

    if len(ratios) == 0:
        return None

    ratios = np.array(ratios)
    idx_local = np.argmin(ratios)
    return indices[idx_local]


def pivotgauss(T, r, s):

    T = np.array(T, dtype=float)
    m, n = T.shape

    pivot = T[r, s]
    if pivot == 0:
        raise ValueError("Pivot nul, pivot de Gauss impossible.")

    # 1) Normaliser la ligne pivot
    T[r, :] = T[r, :] / pivot

    # 2) Annuler les autres éléments de la colonne pivot
    for i in range(m):
        if i != r:
            facteur = T[i, s]
            T[i, :] = T[i, :] - facteur * T[r, :]

    return T


def simplexe(A, b, c, max_iter=100):

    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    c = np.array(c, dtype=float)

    m, n = A.shape


    T = generate_tabinitial(A, b, c)


    base = list(range(n, n + m))

    for it in range(max_iter):

        cbar = T[-1, :-1]


        all_pos, min_val, s = positivite(cbar)


        if all_pos:
            z_opt = T[-1, -1]

            x_opt = np.zeros(n)
            bbar = T[:-1, -1]
            for i, var_index in enumerate(base):
                if var_index < n:
                    x_opt[var_index] = bbar[i]
            return x_opt, z_opt, T


        col_s = T[:-1, s]
        bbar = T[:-1, -1]
        r = rapportmin(bbar, col_s)
        if r is None:
            raise ValueError("Problème non borné inférieurement (aucun rapport positif).")


        T = pivotgauss(T, r, s)


        base[r] = s

    raise RuntimeError("Nombre maximal d'itérations atteint dans le simplexe.")


A_ex = np.array([[1, 1],
                 [1, 2]], dtype=float)
b_ex = np.array([4, 6], dtype=float)
c_ex = np.array([-3, -2], dtype=float)

x_opt, z_opt, T_final = simplexe(A_ex, b_ex, c_ex)

print("=== Résultat avec simplexe maison ===")
print("x* =", x_opt)
print("z* =", z_opt)
print("Tableau final :")
print(T_final)


res = linprog(c_ex, A_ub=A_ex, b_ub=b_ex)
print("\n=== Résultat avec scipy.optimize.linprog ===")
print(res)
print("Optimal value :", res.fun, "\nX :", res.x)


=== Résultat avec simplexe maison ===
x* = [4. 0.]
z* = 12.0
Tableau final :
[[ 1.  1.  1.  0.  4.]
 [ 0.  1. -1.  1.  2.]
 [ 0.  1.  3.  0. 12.]]

=== Résultat avec scipy.optimize.linprog ===
        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -12.0
              x: [ 4.000e+00  0.000e+00]
            nit: 2
          lower:  residual: [ 4.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  1.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  2.000e+00]
                 marginals: [-3.000e+00 -0.000e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0
Optimal value : -12.0 
X : [4. 0.]
