<a href="https://colab.research.google.com/github/dallalysalah/TP-Maths/blob/main/tp4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1, -1], [1, 2]])
b = np.array([[4],[6]])
c = np.array([[3, 2]])

def generate_tabinitial(A, b, c):
    m, n = A.shape
    T = np.zeros((m + 1, n + m + 1))
    T[:m, :n] = A
    T[:m, n:n+m] = np.eye(m)
    T[:m, n+m] = b.flatten()
    T[m, :n] = c
    return T

print(generate_tabinitial(A, b, c))


"""------------------------------------------------------------------------------------------------------------------------------------------------------------------------- """
def positive(v):
    min_val = np.min(v)
    min_idx = np.argmin(v)
    all_pos = np.all(v >= 0)

    if all_pos:
        return True
    else:
        print(f"min = {min_val} à l'indice {min_idx}")
        return False

#exemple
arr = np.array([[0, 1, -3, 2], [0,4,2,1]])


result = positive(arr)
print(f"Result: {result}")

"""------------------------------------------------------------------------------------------------------------------------------------------------------------------------- """
def rapportmin(b, a):
  for i in range(len(a+b)):
    if a[i] > 0:
      x[i]=a[i]/b[i]

  min_index = np.argmin(x)

  return min_index
#exemple
a=np.array([1,2,3])
b=np.array([4,2,7])
x=np.array()


[[ 1. -1.  1.  0.  4.]
 [ 1.  2.  0.  1.  6.]
 [ 3.  2.  0.  0.  0.]]
min = -3 à l'indice 2
Result: False


TypeError: array() missing required argument 'object' (pos 0)